### ISSUE TITLE
Use Django SSL redirect capabilities

### ISSUE THREAD

**Issue by Blu3spirits** [Kiro47/MTU-Transfer-Course-Gatherer#32]
I'm positive Django has an SSL redirect ability. We should use this in the backend so our links
go from this:
```
"http://courses-dev.blu3spirits.com/api/colleges/"
```
to this:
```
"https://courses-dev.blu3spirits.com/api/colleges/"
```
Automatically

**Comment by Kiro47** [comment]
https://github.com/rdegges/django-sslify looks to be about exactly what we want, just need to make sure to allow HTTP on development.

Also, personally of the opinion that I'm not sure if we should enforce this really or just should let the web server itself manage this properly with HSTS.

**Comment by Blu3spirits** [comment]
Ideally what I should be doing is just using upgrade-requests: true with nginx. However, I'm sick of having port 80 open and getting my network poked with drive-bys.

**Comment by Blu3spirits** [comment]
The more I think about this, the more I think I shouldn't do this for the repo as a whole and instead allow the webserver to negotiate this stuff. Closing.
