### ISSUE TITLE
Split Dockerfile into dev/prod

### ISSUE THREAD

**Issue by Blu3spirits** [Kiro47/MTU-Transfer-Course-Gatherer#35]
https://github.com/Kiro47/MTU-Transfer-Course-Gatherer/pull/33#discussion_r419166354

Prod dockerfile should not include seed data and be more geared towards a prod environment.

Dev dockerfile should be kitchen sink, everything needed to get hacking on this project.

**Comment by codetheweb** [comment]
We could go two different ways with dev:
- A fleshed out version of prod, but still doing static builds and using gunicorn
- A dev env, that mounts the local repo as a volume, using `npm start` and `python manage.py runserver`

**Comment by codetheweb** [comment]
I can take this if you want @Blu3spirits. (And any thoughts on the above?)

**Comment by Blu3spirits** [comment]
Have at it @codetheweb 

Dev environment should definitely be running the separate manage scripts. Or using some other module to build/rebuild/redeploy on file change.

**Comment by Blu3spirits** [comment]
I think we should include django debug toolbar in the dev environment as well. It's really valuable for debugging slow responses and showing database statements, among many other uses.
