### ISSUE TITLE
Settle on a different DBMS

### ISSUE THREAD

**Issue by Blu3spirits** [Kiro47/MTU-Transfer-Course-Gatherer#36]
I propose using postgresql, or mariadb for this project rather than sqlite.

Reasons for this:
- A planned expansion of included current/future MTU courses that are being offered so we can relate the transfer courses, to real course objects
- Separate hosts for db/prod site.
- Maria has faster read speeds

What do you guys think?
@Kiro47 @codetheweb

**Comment by codetheweb** [comment]
👍 sounds good to me.

I default to using PostgreSQL, but I don't really have a preference.

Would we still use SQLite for local development?

**Comment by Blu3spirits** [comment]
We could keep SQLite for local dev, I know personally I will just use my own -dev database.

**Comment by codetheweb** [comment]
Combining with #35.

**Comment by Kiro47** [comment]
Whether PostgreSQL or MariaDB doesn't make much of a difference to me personally, I've used both and never found any feature I wanted that wasn't available in both.  I know at one point @Blu3spirits mentioned some specific feature PostegreSQL had that would make live maintenance easier, something to do with syncing.  Do you happen to have a link to what that was?


As for SQLite, that's definitely something we should keep around for development or even lightweight production deployments.  We're still working with a pretty small data set in the grand scheme of things and really have no need to force a full DBMS with what we have.

**Comment by Blu3spirits** [comment]
Do you mean Postgres triggers @Kiro47? As far as live maintenance postgres in general has some neat(but not unique) features that allow you to dump the entire db, save it, change it, and reupload within a few lines of a script.
