### ISSUE TITLE
Add page title and favicon

### ISSUE THREAD

**Issue by Blu3spirits** [Kiro47/MTU-Transfer-Course-Gatherer#44]
Currently, the page title is React App and there is no favicon. We don't specifically need an icon, but we should at least have a page title.

**Comment by Kiro47** [comment]
For note on this, specifically for the logo, we need to take some great care on what we use.  If we make it at all similar to MTU's the UMC has very particular requirements about branding https://www.mtu.edu/umc/resources/download/ . We also could just go with the option of something entirely else not related.

For the page title, I'm not sure what it should be.  Ideally it should be fairly short and to the point, maybe something like `Transfer Courses` ?

**Comment by Blu3spirits** [comment]
I'm very much a fan of not using _anything_ related to MTUs images, in order to keep as far away from any legality issues as possible.

Transfer Courses sounds good to me.

**Comment by codetheweb** [comment]
What are your opinions on using MTU's yellow color for the logo / UI elements?

**Comment by Kiro47** [comment]
Personally, my skill out of 100 in aesthetics is about a 5.

However, I think using it as an accent color might be nice?
I really don't know without an example tbh, as much as I hate to be that way.

**Comment by codetheweb** [comment]
Yeah, I was just asking more from a branding requirements / legality perspective if it was even possible.

I have used their yellow in other projects without issue, and I doubt they'd have much of a case to come after us for using 1 color anyways.

**Comment by Kiro47** [comment]
They don't have any legal authority on the color #ffcd00 itself, only possibly when used in conjunction with black #000000.  Which we're not using a pure black like that that I'm aware of (besides text), so I wouldn't think it'd be an issue.

**Comment by Blu3spirits** [comment]
I used that yellow and then a grey that we have in place on the site already (or something really close) for the favicon.
