### ISSUE TITLE
Speed up inital site load

### ISSUE THREAD

**Issue by codetheweb** [Kiro47/MTU-Transfer-Course-Gatherer#49]
[Google's PageSpeed](https://developers.google.com/speed/pagespeed/insights) tool has a bunch of suggestions.  Most notably, it doesn't seem that Whitenoise is working properly - static files are not being gzip'ed like they're supposed to.
The cache TTL is also only 1 minute but should be much larger.

**Comment by Blu3spirits** [comment]
Found some relevent docs on gzip and whitenoise:
https://docs.djangoproject.com/en/3.0/ref/middleware/#gzip-middleware
https://stackoverflow.com/questions/47579234/should-whitenoise-auto-compress-static-files-how
We need to make sure the Accept encoding: gzip is set (I think it should be default?)

Django cache can bet set via:
https://docs.djangoproject.com/en/3.0/topics/cache/
