### ISSUE TITLE
Typescript not installed + other misc bugs

### ISSUE THREAD

**Issue by Blu3spirits** [Kiro47/MTU-Transfer-Course-Gatherer#67]
On building the latest PR:
```
We detected TypeScript in your project (src/index.tsx) and created a tsconfig.json file for you.

It looks like you're trying to use TypeScript but do not have typescript installed.
Please install typescript by running npm install typescript.
If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-27T15_56_49_803Z-debug.log
```

I managed to fix this on my deployment by doing this:
```
diff --git a/Dockerfile b/Dockerfile
index 6ee7fad..a14f84e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,6 +10,7 @@ WORKDIR /app/webapp
 COPY webapp/package*.json ./

 RUN npm ci --only=production
+RUN npm install typescript

 # Copy source
 COPY webapp/src ./src
@@ -18,6 +19,7 @@ COPY webapp/public ./public
 # Build app
 ARG REACT_APP_ENDPOINT
 ENV REACT_APP_ENDPOINT=$REACT_APP_ENDPOINT
+ENV SKIP_PREFLIGHT_CHECK=true
 # For public resources
 ENV PUBLIC_URL=/static
```

Also seems like the theme is no longer saved to local storage

@codetheweb 

I'm unsure how to fix the theme saving at this moment.

**Comment by codetheweb** [comment]
Looks like the Dockerfile is running `npm ci --only=production`, and TypeScript is listed as a dev dependency.

Theme saving appears to be working for me (tried clearing local storage to re-init it).

**Comment by Blu3spirits** [comment]
> Theme saving appears to be working for me (tried clearing local storage to re-init it).


I'll toss up a dev instance and test a few more times on my next work break. Also created #68

**Comment by Blu3spirits** [comment]
> I'll toss up a dev instance and test a few more times on my next work break. Also created #68


Tossed up my local instance in case the problem was the deployment and yes, _saving_ works. On page reload, however the theme does not properly load in and defaults to the system_set one. 

I did some debugging and the issue is in the isInitialThemeLight selector.

When dark mode is set (and no prefers-color-scheme variable is set) to localstorage the selector still returns true, ignoring the output of the local storage.

```diff
   if (storedTheme === 'light') {
     return true;
+  } else if (storedTheme === 'dark') {
+    return false;
+  } else {
+    return !window.matchMedia('(prefers-color-scheme: dark)').matches;
   }
-
-  return !window.matchMedia('(prefers-color-scheme: dark)').matches;
 };
```

This is what I did to fix it, it's not at all elegent. But it will give priority to `storedTheme` first and then fall back to system preference.

**Comment by codetheweb** [comment]
Ah, I see (bug can be reproduced if `prefers-color-scheme: light` is true and theme button is clicked so page theme changes to dark).
